### ISSUE TITLE
CAS is not supported by the client. Minimum client version is 6.0

### ISSUE THREAD

**Issue by tofra** [lkrms/homebrew-misc#1]
I get the message `CAS is not supported by the client. Minimum client version is 6.0`. It is already fixed in openconnect https://gitlab.com/openconnect/openconnect/-/issues/651#note_1577713956 commit https://gitlab.com/openconnect/openconnect/-/commit/50428ca0f3165382a4ee13e0469b63cd9e52c9e5. Should we wait until it's released?

**Comment by lkrms** [comment]
It looks like this issue is with openconnect itself, which is an unbundled dependency of the gp-saml-connect formula, so soon after the fix makes its way to a release, you should be able to `brew upgrade` to benefit from it 😊
